### ISSUE TITLE
Dynamo cannot find Ladybug's installation folder

### ISSUE THREAD

**Issue by koubaaleila** [ladybug-analysis-tools/honeybee-grasshopper#88]
Hello! Ladybug won't work on dynamo! what is the problem??i tried to install it again but i doesn't work.

![image](https://user-images.githubusercontent.com/24694950/39192242-aa79efb2-47d0-11e8-9c56-56363e7b5cde.png)

**Comment by koubaaleila** [comment]
I installed dynamo studio, and ladybug won't work neither!
![image](https://user-images.githubusercontent.com/24694950/39198684-91f3c774-47df-11e8-8a38-bc041ba6fefc.png)

**Comment by mostaphaRoudsari** [comment]
@koubaaleila, I think it's because you're trying to run it from Dynamo Studio but you have installed it from Dynamo for Revit.
 
Are the files located under `C:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Ladybug`? For Dynamo Studio you should copy the files under `C:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Core\1.3\packages\Ladybug`

**Comment by koubaaleila** [comment]
i tried for Revit dynamo and it doesn't work neither. The files are on the right place

    Le mardi 24 avril 2018 à 18:28:29 UTC+1, Mostapha Sadeghipour Roudsari <notifications@github.com> a écrit :  
 
 
@koubaaleila, I think it's because you're trying to run it from Dynamo Studio but you have installed it from Dynamo for Revit.

Are the files located under C:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Ladybug? For Dynamo Studio you should copy the files under C:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Core\1.3\packages\Ladybug

**Comment by mostaphaRoudsari** [comment]
Can you follow the directions here: https://github.com/ladybug-tools/honeybee-dynamo/issues/42#issuecomment-285682094

This should tell us more on why it can't find the installation folder.

**Comment by koubaaleila** [comment]
C:\Users\LAÏLA\AppData\Roaming\Dynamo\Dynamo Core\1.3\packages\Ladybug

**Comment by mostaphaRoudsari** [comment]
The path is correct which means it's most likely because of `Ï` in `LAÏLA`.

Use Settings > Manage Node and Packages Path to define a new folder with no special characters and move the package folder there. Once you do that Honeybee should be able to find the installation folder and import the libraries.

**Comment by koubaaleila** [comment]
thank you. It's resolved
